version: "3"

services:
  app:
    build: .
    container_name: parallelproject
    command: uvicorn --host 0.0.0.0 --port 7000 main:app --reload
    ports:
      - "7000:7000"
    networks:
      - main
    restart: always

networks:
  main:
    driver: bridge


